# Generated by Django 4.0.3 on 2022-06-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='posts',
            new_name='post',
        ),
    ]
